"""Adiciona assigned_editor_id em Article

Revision ID: da1de88d8ac2
Revises: 
Create Date: 2025-06-03 08:18:42.459061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1de88d8ac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_editor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_editor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_editor_id')

    # ### end Alembic commands ###
